[package]
name = "bagit"
version = "0.1.0"
edition = "2021"

[features]
default = ["generate"]
generate = []

[dependencies]
thiserror = "1"
tokio = { version = "1", features = ["fs", "rt", "io-util"] }
digest = "0.10"
hex = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
sha2 = "0.10"
md-5 = "0.10"
tempfile = "3"
