name: Coverage
on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path ./target/lcov.info
      - name: Report code coverage
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./target/lcov.info
