name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo build --no-default-features
      - run: cargo build --examples --all-features
      - run: cargo test --all-features

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - run: cargo clippy --all-targets --all-features
      - run: cargo fmt --check

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo run --example read_zstd_archive -- ./tests/sample-bag.tar.zst
      - run: cargo run --example blake3_generate --features="generate" -- ${{ runner.temp }}/test_bag
